name: Build Nativa (GraalVM) & Upload (Actions + Release)

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]

    runs-on: ubuntu-24.04-${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK (GraalVM)
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '25'
          cache: 'maven'

      - name: Build native image (skip tests)
        run: |
          chmod +x mvnw
          ./mvnw -Pnative -DskipTests native:compile

      - name: Package artifact (zip)
        id: pack
        run: |
          set -euo pipefail
          BINPATH=$(find target -maxdepth 1 -type f -perm -111 -printf "%p %s\n" \
            | sort -k2 -nr | head -n1 | awk '{print $1}')

          APPNAME=$(basename "$BINPATH")
          SUFFIX="${{ matrix.arch }}-${GITHUB_RUN_ID}"
          ZIPNAME="${APPNAME}-linux-${SUFFIX}.zip"

          echo "Jalankan: ./${APPNAME}" > target/HOW_TO_RUN.txt
          (cd target && zip -r "../${ZIPNAME}" "$APPNAME" HOW_TO_RUN.txt >/dev/null)

          sha256sum "${ZIPNAME}" | tee "${ZIPNAME}.sha256"

          echo "zip=${ZIPNAME}" >> "$GITHUB_OUTPUT"
          echo "checksum=${ZIPNAME}.sha256" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pack.outputs.zip }}
          path: |
            ${{ steps.pack.outputs.zip }}
            ${{ steps.pack.outputs.checksum }}
